### ISSUE TITLE
Add support for background task scheduling in iOS

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/SwiftSyft#36]
In order to properly execute training plans, we must do so in a background task. This allows for training to take place without a visual API (as a library of another app), and do so separate from the main thread.

**Comment by mjjimenez** [comment]
Background   Tasks Type | iOS 12 | iOS 13 | Use Case | Estimated   background time | CPU Monitor   Enabled (Shuts down CPU Intensive tasks) | API Handler
-- | -- | -- | -- | -- | -- | --
App Refresh | x | x | Periodically   pull new content | 30 seconds | Enabled | Background   hook is in application specific code. Can't be used by a library
Background   Push Notificaiton | x | x | Push   new content to device | 30 seconds | Enabled | Background   hook is in application specific code. Can't be used by a library
Background   Task | x | x | Ask   for extension of execution time when app goes into background | 30 seconds | Enabled | Background   code can be executed anywhere in the app
Background   Task Scheduler |   | x | Schedule   background task | Possible to extend   past 30 seconds into minutes | Disabled   when background task requires external power | Background   code can be executed anywhere in the app




## iOS 12 and below

1. **Background app refresh**
2. **Background/silent push notification**

*Disadvantages*
* Setting up these background modes are out of the scope of a library/framework because they need to be set-up per app. These features are configured and called using application specific code.
* The code to execute the background task can only be located in an application hook. The app will be launched from the background so the syft client will not remember any closures saved from when the app was open.
* Can be shut-off by the OS if CPU activity is too high

3. **Background tasks**

*Disadvantages*
* Can only be executed before the app is backgrounded to request additional execution time.
* Can be shut-off by the OS if CPU activity is too high


## iOS 13 

1. **Background task scheduler**

*Advantages*
* Made specifically for our use case (ML training)
* Can be used anywhere in the app.
* You can specify requirements for network connectivity and external power.
* Can execute CPU intensive tasks.

*Disadvantages*
* There is some additional application specific set-up to use this
	* Turn on background modes for the app.
	* Create an identifier for each type of scheduled background task.
* There is no guarantee when your task will be executed. It depends on a lot of factors including other background tasks scheduled in the system.
* In order to allow CPU intensive tasks, you need to request a background task request that will only work when the device is being charged.
* Doesn’t repeat automatically, you have to reschedule the next task.
* Can only be used if your app was used recently. No specific information on how recent, but recommendation is 1 week.
* If an app’s background task is running when it is opened, the background task is stopped.
* There’s no way for me to resume a background task.

**Comment by cereallarceny** [comment]
@mjjimenez **Excellent research.**

I'm curious after knowing all this if supporting iOS 12 is even worth it. Did we hear if the PyTorch team was able to execute code for longer than 30 seconds OUTSIDE an app on iOS 12? I can imagine that running  a plan in app would be quite trivial as you can always keep the app alive... but a background task? That could be a bit more challenging.

@karlhigley would also love to hear your thoughts.

**Comment by karlhigley** [comment]
If it’s causing significant headaches, I’d drop iOS 12 support.

**Comment by mjjimenez** [comment]
@cereallarceny I haven't heard back from them yet. We'll proceed with developing the client with iOS 13 API for now.

**Comment by cereallarceny** [comment]
No worries. Feel free to also remove any iOS 12 specific code and dependencies as well. :)

**Comment by mjjimenez** [comment]
Closed in #97 . Background execution is now the responsiblity of the library user.
